### ISSUE TITLE
Simulating distortion caused by rotation

### ISSUE THREAD

**Issue by u-sj** [RobotecAI/o3de-rgl-gem#22]
The current behavior seems to be that the entire scene is captured at once regardless of the sensor frequency. Real rotating lidar sensors collect points over time which causes distortion when objects are moving relative to the sensor.

Would it be possible to simulate distortions caused by movement? How big would the performance hit be? Would the limiting factor for "subsections" be the frame rate?
Point specific time stamps in the ROS message would be great with this feature.

**Comment by alek-kam-robotec-ai** [comment]
Hi @u-sj, thank you for your patience! Adding support for this feature is not planned in the immediate future. Nevertheless, the Robotec GPU Lidar does support velocity distortion which is only compatible with static objects due to its ongoing development. This functionality may be incorporated into the Gem as it reaches a more polished stage.
